Limit the recursion depth when syncing advertisements
filecoin-project/storetheindex pull request #176
Opened 2022-01-26 17:53 UTC by masih

By default sync at most 400 unseed advertisements and expose ingest
config parameter to override it.

2022-01-26 17:57 UTC, willscott commented
if we get more than 400 behind the head, will this cause them all to get synced but over multiple sessions, ore will we end up loosing the old ones?

2022-01-26 17:58 UTC, masih commented
The latter

2022-01-27 20:41 UTC, gammazero approved these changes

2022-01-27 20:48 UTC, gammazero requested changes
Need to fix test

2022-01-28 14:25 UTC, gammazero approved these changes

2022-01-28 17:52 UTC, merged